# Generated by Django 4.2.3 on 2023-07-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
